### ISSUE TITLE
list index out of range error

### ISSUE THREAD

**Issue by kayselmecnun** [kijai/ComfyUI-segment-anything-2#3]
![image](https://github.com/user-attachments/assets/c24bc717-e308-4bf3-81ce-d4dd3877f607)

**Comment by kijai** [comment]
Probably because the node is trying to select indexes 0 and 1, while there only seems to be one?

**Comment by kijai** [comment]
Fixed that case anyway so that it doesn't error out.

**Comment by kayselmecnun** [comment]
I'm not sure you published the fix but still getting the same error after updating the node
![image](https://github.com/user-attachments/assets/53262a5b-f3a5-4f2b-be09-2cbec2df37e6)

**Comment by kijai** [comment]
> I'm not sure you published the fix but still getting the same error after updating the node ![image](https://private-user-images.githubusercontent.com/130417464/353757644-53262a5b-f3a5-4f2b-be09-2cbec2df37e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTgyNTcsIm5iZiI6MTcyMjQxNzk1NywicGF0aCI6Ii8xMzA0MTc0NjQvMzUzNzU3NjQ0LTUzMjYyYTViLWYzYTUtNGYyYi1iZTA5LTJjYmVjMmRmMzdlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwOTI1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMTk2ZGQ0NWM5YTJiNjAxYzM3NGJhMTY4NGMzYzYzM2Q2ZDhkY2M1NDdjZWI4NzkyZmU4ZGI3MTNkMzFkMjFlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.QHQkJBjSbG7DL-H2wrk7W2i3Fa-gYdsjZeEddn9jgwc)

Possibly your Florence2 nodes are not updated?

**Comment by kayselmecnun** [comment]
Yeah that was it, updating your Florence-2 nodes solved it. Thanks  a lot
